global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "identityforge"
    metrics_path: /system/metrics
    static_configs:
      - targets:
          - "host.docker.internal:5000"
          - "backend:5000"